# permissions for end users to view kafkaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkacluster-viewer-role
rules:
- apiGroups:
  - kafka.cmos.com
  resources:
  - kafkaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka.cmos.com
  resources:
  - kafkaclusters/status
  verbs:
  - get
